### ISSUE TITLE
how to access the trial object? maybe the plugin should implement a function allowing to do that? 

### ISSUE THREAD

**Issue by danielgafni** [toshihikoyanase/hydra-optuna-sweeper#4]
This can be very useful. 
Examples: trial pruning, custom user attributes, etc.

**Comment by michelkok** [comment]
I'd like something like this as well. I have now done it via the [`custom_search_space`](https://hydra.cc/docs/plugins/optuna_sweeper/#experimental--custom-search-space-optimization) but it's definitely a hack. 
It would be very useful if in the same way some sort of `callback` could be provided such that the trial object becomes exposed. Or just somehow pass the `Trial` down to the decorated function, although that likely allows modifying `hydra` itself.

The way I set it up now:
```
hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: sqlite:///trials.db
    n_trials: 20
    n_jobs: 1
    params:
      x: range(-5.5, 5.5, step=0.5)
      y: choice(-5 ,0 ,5)
      z: choice([0, 1], [2, 3], [2, 5])
    custom_search_space: package.run.configure
```

```
def configure(_, trial: Trial) -> None:
    trial.set_user_attr("experiment_db_id", 123456)
```

P.s. I also asked this question on [StackOverflow](https://stackoverflow.com/questions/72897321/store-user-attributes-in-optuna-sweeper-plugin-for-hydra) but didn't get an answer (yet).
